# Generated by Django 5.2.17 on 2026-08-11 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('authentications', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_round',
            field=models.ForeignKey(blank=True, db_column='current_round_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobround'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.jobopening'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='authentications.student'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'job')},
        ),
    ]
