# Generated by Django 5.2.17 on 2026-08-11 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('job_id', models.AutoField(db_column='job_id', primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('role_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('apply_link', models.CharField(max_length=255)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('max_career_gap_months', models.IntegerField(default=24)),
                ('allowed_branches', models.CharField(max_length=255)),
                ('passout_year', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to='authentications.coordinator')),
            ],
            options={
                'db_table': 'job_openings',
            },
        ),
        migrations.CreateModel(
            name='JobRound',
            fields=[
                ('round_id', models.AutoField(db_column='round_id', primary_key=True, serialize=False)),
                ('round_order', models.IntegerField()),
                ('round_name', models.CharField(max_length=100)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='jobs.jobopening')),
            ],
            options={
                'db_table': 'job_rounds',
                'ordering': ['round_order'],
                'unique_together': {('job', 'round_order')},
            },
        ),
    ]
